version: '3.8'

services:
  # FastAPI backend service
  backend:
    build: 
      context: ./crud-spring
      dockerfile: Dockerfile
      
      
    ports:
      - "${BACKEND_PORT}:8000"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      MYSQL_HOST: ${MYSQL_HOST}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
   
    depends_on:
      - mysql

  # Angular frontend service
   

  frontend:
    build:
      context: ./crud-angular
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  # Mysql service
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/data/db

volumes:
  mysql-data:
